### ISSUE TITLE
小米3点login直接闪退

### ISSUE THREAD

**Issue by tinybright** [Jeffmen/Git.NB#2]
> `FATAL EXCEPTION: main
>                                                                    Process: com.example.gitnb, PID: 25544
>                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.gitnb/com.example.gitnb.module.GitHubAuthorizeActivity}: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
>                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2189)
>                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2238)
>                                                                        at android.app.ActivityThread.access$800(ActivityThread.java:138)
>                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1201)
>                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                                        at android.os.Looper.loop(Looper.java:136)
>                                                                        at android.app.ActivityThread.main(ActivityThread.java:5016)
>                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
>                                                                        at java.lang.reflect.Method.invoke(Method.java:515)
>                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
>                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
>                                                                        at dalvik.system.NativeStart.main(Native Method)
>                                                                     Caused by: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
>                                                                        at android.support.v7.app.AppCompatDelegateImplV7.setSupportActionBar(AppCompatDelegateImplV7.java:198)
>                                                                        at android.support.v7.app.AppCompatActivity.setSupportActionBar(AppCompatActivity.java:99)
>                                                                        at com.example.gitnb.app.BaseSwipeActivity.setContentView(BaseSwipeActivity.java:69)
>                                                                        at com.example.gitnb.module.GitHubAuthorizeActivity.onCreate(GitHubAuthorizeActivity.java:37)
>                                                                        at android.app.Activity.performCreate(Activity.java:5248)
>                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
>                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2153)
>                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2238) 
>                                                                        at android.app.ActivityThread.access$800(ActivityThread.java:138) 
>                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1201) 
>                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
>                                                                        at android.os.Looper.loop(Looper.java:136) 
>                                                                        at android.app.ActivityThread.main(ActivityThread.java:5016) 
>                                                                        at java.lang.reflect.Method.invokeNative(Native Method) 
>                                                                        at java.lang.reflect.Method.invoke(Method.java:515) 
>                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792) 
>                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608) 
>                                                                        at dalvik.system.NativeStart.main(Native Method) `

**Comment by Jeffmen** [comment]
5.0以下的版本actionbar问题，现在我已更新代码和APK，在4.4系统测试过，没有问题，但是界面和5.0以上差好多

**Comment by Jeffmen** [comment]
谢谢你提供的错误log，
