### ISSUE TITLE
为啥打开github是以浏览器打开网页的方式

### ISSUE THREAD

**Issue by zengcanxiang** [Jeffmen/Git.NB#9]
我打开应用每次总是会显示动画，我觉得，应该和github一样，不要让第二次看到登录界面，
然后我使用他的过程是在一个标题为autoo什么的界面，用浏览器打开github网页一样的体验，不知道为什么，看不到作者你图片上展示的界面。而且不管点击返回箭头还是按返回键，总是会退出应用，很不爽......

**Comment by Jeffmen** [comment]
动画的页面后面我会去掉的。
你说的autoo页面能截图我看看么？APP里面只有登录页面和源码文件会有webview展示。其它页面是没有的。
而且不管点击返回箭头还是按返回键---这个Back和箭头应该是可以退出页面的，不是退出应用。
你用的是什么系统呀？

**Comment by zengcanxiang** [comment]
那应该是我卡在你的登录界面没有进去，我在去试一试。如果是卡在登录界面，那么都说的通了
